### ISSUE TITLE
dunst notifications show on top of lock screen

### ISSUE THREAD

**Issue by victorz** [Raymo111/i3lock-color#247] opened 2021-12-16 20:45 UTC
Not sure if this should be filed on the dunst project or this project. Not tested yet whether this happens on regular i3lock, but I'm using this package, so here goes.

## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

`dunst` notifications show on top of the lock screen.

## Expected Behavior

Notifications should probably not show on top of the lock screen? :man_shrugging: Not sure whether or not this is intended behavior.

## Reproduction Instructions

Run something like: `i3lock; sleep 1 && notify-send "Uh, I don't think I should be able to see this."`

After 1 second, the notification shows visible, despite having locked the screen.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.4 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2021 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] [AUR package](https://aur.archlinux.org/packages/i3lock-color/)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment] 2021-12-16 20:57
Duplicate of #210.

**Closed as completed** 2021-12-16 20:57 UTC
