### ISSUE TITLE
Truncated time and date

### ISSUE THREAD

**Issue by simonkrogmann** [Raymo111/i3lock-color#59] opened 2017-12-20 13:13 UTC
For large font sizes and/or long format strings the time and date may get truncated. The reason for this seems to be `#define CLOCK_WIDTH 400` in unlock_indicator.c which hardcodes the width of the text widget.

**Comment by PandorasFox** [comment] 2017-12-20 13:41
Sadly, it's pretty much a necessity due to how centering the Cairo contexts works.

I'm currently waiting on a patch to get into upstream i3lock before I work on redoing font/text handling; I may be able to fix that then.

**Comment by PandorasFox** [comment] 2018-01-20 04:54
Should be fixed with 6b943766dae08295e8ecdeb81d126e9f06f39194 in the `dev` branch.

I fixed this as part of a pretty big refactor, so there might be a few regressions on that branch currently.

**Comment by PandorasFox** [comment] 2018-01-23 18:27
This has been pushed to master now and should be working fine.

![image](https://user-images.githubusercontent.com/3235827/35293239-2009e3ea-0041-11e8-8222-800b4b5ad1ff.png)

**Closed as completed by PandorasFox** 2018-01-23 18:27 UTC
