### ISSUE TITLE
i3lock unrecognized option --textcolor

### ISSUE THREAD

**Issue by jparrill** [Raymo111/i3lock-color#99] opened 2018-07-04 05:55 UTC
Hi there,

I downloaded and compiled the last version of master branch from here:
```
➜  i3lock-color git:(master) ✗ i3lock-color --version
i3lock-color: version 2.11-c-15-g594b5c6 (2018-06-27, branch "master") © 2010 Michael Stapelberg
```

In some places I found scripts to lock the wm with a fancy view, but all of them gets me an error:
```
unrecognized option '--textcolor=ffffffff'
```

Compilation parameters:
```
autoreconf -i && ./configure && make
```

Any ideas?

**Comment by sylveon** [comment] 2018-07-04 20:45
Dupe of #73

**Closed as completed** 2018-07-05 13:10 UTC
