### ISSUE TITLE
Media keys are not passed

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [Raymo111/i3lock-color#267] opened 2022-09-04 22:45 UTC
## This issue is a....
<pre>
[X] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior
`i3lock --pass-media-keys` does not pass media keys.

## Expected Behavior
`i3lock --pass-media-keys` should pass media keys.

## Reproduction Instructions
OS is Debian 10. Desktop environment is MATE. I can play and pause media using the media keys via xbindkeys. I lock the screen with: `i3lock --pass-media-keys`. I would expect the media keys to continue to function as normal. The keys in question are `m:0x0 + c:208` and `m:0x0 + c:209`, which correspond to XF86AudioPlay and XF86AudioPause. (I'm using the keycode numbers instead of the names due to what seems to be a problem with xbindkeys, but it should work either way)

If I had to guess, I think the problem has something to do with how i3lock interacts with MATE. I have used i3lock-color in the past with fluxbox (keys are bound in fluxbox's keys file) and it worked at that time. I think maybe when the screen is locked, some component of MATE is intercepting the keys somehow and they are not getting passed correctly along to xbindkeys, but I am just guessing.

## Environment
<pre>
i3lock version: 2.13.c.4, also tried with 2.13.c.4-37-gaeb9982.
</pre>

Where'd you get i3lock-color from?
<pre>
[ ] AUR package (which one?)
[X] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

**Comment by Raymo111** [comment] 2022-09-04 22:59
Closing as duplicate of #136

**Closed as completed by Raymo111** 2022-09-04 22:59 UTC
